### ISSUE TITLE
Unable to connect to LDAP as per the READ.ME instructions

### ISSUE THREAD

**Issue by bossey1** [downtownallday/mailinabox-ldap#16]
Hi

Following the https://github.com/downtownallday/mailinabox-ldap#readme connection instructions don't work for me.

When running remote-nectcloud-use-miab.sh I get an error that the remote ldap cannot be connected.

I've checked that firewall port 636 is open and listening.
Yet I get the error.

For example using:
<remote-nextcloud-use-miab.sh /var/www/nextcloud my-existingnextcloud-admin-ID my-ID-PASS MIAB-LDAP-BOX-FQDN H8QxEi1IM7JtiDoLgXblahblahblah-as-supplied-by-MIAB-LDAP-install SSMTP_AUTH_USER SSMTP_AUTH_PASS

I get:
Testing MiaB-LDAP connection...
Unable to contact ldaps://myFQDN-of-Mailinabox-LDAP box
   base=dc=mailinabox
   user=cn=nextcloud,ou=Services,dc=mailinabox
   error code=255
   msg= ldap_initialize( ldaps://brnpomaa.beosribo.co.uk:636/??base )
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)

You may need to permit access to the ldap server running on brnpomaa.beosribo.co.uk
On brnpomaa.beosribo.co.uk execute:
   ufw allow proto tcp from 127.0.0.1 to any port ldaps
   ufw allow proto tcp from xxx.xxx.xxx.xxx to any port ldaps

I'll turn on more debugging output on the next attempt
Press [enter] when ready, or "no" to give up: 

Why is it showing:
<base=dc=mailinabox> as opposed to the MIAB-LDAP Domain name and is there opportunity to change this?
Is it trying to connect wrong directory?

I'm soory I looked elswhere to send query but there is no obvious link here.

Thanks

**Comment by downtownallday** [comment]
On the miab-ldap server did you run `ufw allow proto tcp from $ip to any port ldaps`, where $ip is the ip-address of your Nextcloud server (the host where you're running remote-nextcloud-use-miab.sh).

**Comment by bossey1** [comment]
> On the miab-ldap server did you run `ufw allow proto tcp from $ip to any port ldaps`, where $ip is the ip-address of your Nextcloud server (the host where you're running remote-nextcloud-use-miab.sh).

Yes

$- ufw status numbered
Status: active

     To                         Action      From
     --                         ------      ----
[ 1] 8879                       LIMIT IN    Anywhere                  
[ 2] 53                         ALLOW IN    Anywhere                  
[ 3] 465/tcp                    ALLOW IN    Anywhere                  
[ 4] 587/tcp                    ALLOW IN    Anywhere                  
[ 5] 993/tcp                    ALLOW IN    Anywhere                  
[ 6] 995/tcp                    ALLOW IN    Anywhere                  
[ 7] 4190/tcp                   ALLOW IN    Anywhere                  
[ 8] 80/tcp                     ALLOW IN    Anywhere                  
[ 9] 443/tcp                    ALLOW IN    Anywhere                  
[10] 25/tcp                     ALLOW IN    Anywhere                  
[11] 25                         ALLOW OUT   Anywhere                   (out)
[12] 3389/tcp                   ALLOW IN    Anywhere                  
[13] 22/tcp                     LIMIT IN    Anywhere                  
[14] 55414:55415/tcp            ALLOW IN    Anywhere                  
[15] 636/tcp                    ALLOW IN    Open for testing           
[16] 636/tcp                    ALLOW IN    x.x.x.x IP of Nextcloud            
[17] 389/tcp                    ALLOW IN    x.x.x.x IP of Nextcloud            
[18] 636/tcp                    ALLOW IN    127.0.0.1

**Comment by downtownallday** [comment]
From the nextcloud server, try `ldapsearch -d 9 -H ldaps://<hostname of miab-ldap server>` and please post output.

**Comment by bossey1** [comment]
Solved.
The install setup ufw and enabled it so the result was double nat with hosting firewall. I simply forgot about the hosting providers firewall. Turned ufw off then disabled with <systemctl disble> the ldap setup then completed successfully.

Thanks

Bernie
