### ISSUE TITLE
Major update fails due to errorneous schema migration/setup

### ISSUE THREAD

**Issue by dumblob** [downtownallday/mailinabox-ldap#18]
Today I wanted to update one miab-ldap machine with ~540 days uptime (yeah, I did not pay much attention to updates :cry:) and got this error:

```
root@bmw:~/mailinabox-ldap# ./setup/start.sh -h
No ecrypted HDD found at /home/user-data.HDD, not mounting

Running migration to Mail-in-a-Box LDAP #1...
Migrating users and aliases from sqlite to ldap
Installing OpenLDAP server...
Waiting for slapd to start...ok
Adding 'mfa-totp' schema
ldap_add: Other (e.g., implementation specific) error (80)
        additional info: olcObjectIdentifier: OID MiabLDAProot:1 not recognized

Error running the migration script:

Command '['setup/ldap.sh', '-v']' returned non-zero exit status 80.

Your system may be in an inconsistent state now. We're terribly sorry. A re-install from a backup might be the best way to continue.
Traceback (most recent call last):
  File "setup/migrate.py", line 461, in <module>
    run_miabldap_migrations()
  File "setup/migrate.py", line 440, in run_miabldap_migrations
    raise e
  File "setup/migrate.py", line 431, in run_miabldap_migrations
    migration_func(env)
  File "setup/migrate.py", line 227, in migration_miabldap_1
    shell("check_call", ["setup/ldap.sh", "-v"])
  File "management/utils.py", line 141, in shell
    ret = getattr(subprocess, method)(cmd_args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['setup/ldap.sh', '-v']' returned non-zero exit status 80.
root@bmw:~/mailinabox-ldap# ./setup/ldap.sh -v
Installing OpenLDAP server...
Waiting for slapd to start...ok
Adding 'mfa-totp' schema
ldap_add: Other (e.g., implementation specific) error (80)
        additional info: olcObjectIdentifier: OID MiabLDAProot:1 not recognized
root@bmw:~/mailinabox-ldap# echo $?
80
root@bmw:~/mailinabox-ldap# 
```

It seems to originate from the fact that in the meantime the totp functionality was added and for some reason the following code does not handle the upgrade just right:

https://github.com/downtownallday/mailinabox-ldap/blob/6ff93bb87e86fde270da5b667ab89fe86eab7364/setup/ldap.sh#L350-L369

Any suggestions how to overcome this issue?

Thanks a lot for tirelessly maintaining this awesome fork!

**Comment by downtownallday** [comment]
HIf you already have miab-ldap installed, it shouldn't be running migration step 1 (convert sqlite to ldap). Only migration step 2 should run, which will update the schema so setup/ldap.sh will run properly.

Do you have a `STORAGE_ROOT/mailinabox-ldap.version` file? It should probably contain the number "1".

**Comment by downtownallday** [comment]
STORAGE_ROOT is usually /home/user-data

**Comment by dumblob** [comment]
```
root@bmw:~# cat /home/user-data/mailinabox.version 
13
```

**Comment by dumblob** [comment]
```
root@bmw:~# ls -l /home/user-data/mailinabox.version 
-rw-r--r-- 1 user-data user-data 3 Oct 22  2020 /home/user-data/mailinabox.version
```
This `ctime` suggests that this file was not overwritten since 2020.

**Comment by dumblob** [comment]
There seems to be no `mailinabox-ldap.version` file:

```
root@bmw:~# find /home/user-data/ -iname '*mailinabox-ldap.version*'
root@bmw:~# echo $?
0
```

**Comment by downtownallday** [comment]
My recommendation: make sure you have a backup if you haven't done that already. Then create a mailinabox-ldap.version file containing the character "1" `echo -n 1 > /home/user-data/mailinabox-ldap.version`, then run setup.

**Comment by dumblob** [comment]
Nice idea! That seems to have helped. If there is anything weird I will notice later, I will come back :wink:.

Thanks a lot!
