### ISSUE TITLE
ldap_modify: Other (e.g., implementation specific) error (80) 

### ISSUE THREAD

**Issue by hungrymonkey** [downtownallday/mailinabox-ldap#21]
Hi Downtownallday,

I have been getting this error `ldap_modify: Other (e.g., implementation specific) error (80)`. My instance keeps hanging during the openssl self-signed key setup. I ended up hitting ctrl+c to stop the script printing "....." for minutes. When I rerun `setup.sh`, ldap throws the error.

Versions tested

v60.1
v61

Not Tested
v62

## Step to reproduce

1. Start a fresh Ubuntu 22.04 instance
2. `apt update && apt upgrade`
3. Pull v61
4. Rerun `setup/start.sh`
5. Hangs on generating pem key. The console keeps printing "..........."
6. Ctrl+C
7. Rerun `setup/start.sh`

## Expected outcome.

1. Openldap will continue

## Observed Outcome

`ldap_modify: Other (e.g., implementation specific) error (80)`

## Tested Fixes.

N/A

## Preliminary Research

I checked stackoverflow and they suggest this fix.

```

In my specific case, I was having this error and I literally spent days scouring the Web for an answer. It turned out in my case that the order matters. The correct order was:

    olcTLSCACertificateFile,
    olcTLSCertificateKeyFile,
    olcTLSCertificateFile.

Until the order of the attributes in my file was the one above, I was having that dreaded and unhelpful "ldap_modify: Other (e.g., implementation specific) error (80)" message.
```
https://stackoverflow.com/questions/51745010/ldap-modify-other-e-g-implementation-specific-error-80

I am going to try it if I see it happens again.

https://github.com/downtownallday/mailinabox-ldap/blob/master/setup/ldap.sh#L436

**Comment by crystalscript** [comment]
Thanks for stopping by and thanks for the research you did. Let me know how it goes. I didn't know about the order.

**Comment by downtownallday** [comment]
Apologies for the username. I'm maintaining another project as crystalscript...

**Comment by hungrymonkey** [comment]
Hi Downtownallday,

Thanks for help maintaining the repo. OSS dies when nobody contributes. I am taking my time to look at this issue. 

```
Primary Hostname: box.punches.duckdns.org
Public IP Address: 
Private IP Address:  
Mail-in-a-Box Version:  v0.52-398-g276ceca
```

I have to admit. The tags and versioning is quite messy.  I did a git checkout v60 and it return v0.52. I might test the latest version in ldap-mailinthebox. The Openssl doesn't happen in v62. I might as well test the upgrade path from the suppose v57.


The changes below didn't fix the issue above.
```
:~/mailinabox$ git diff
diff --git a/setup/ldap.sh b/setup/ldap.sh
index 2688744..2fc98ad 100755
--- a/setup/ldap.sh
+++ b/setup/ldap.sh
@@ -436,12 +436,13 @@ olcLogLevel: config stats shell
 replace: olcTLSCACertificateFile
 olcTLSCACertificateFile: /etc/ssl/certs/ca-certificates.crt
 -
-replace: olcTLSCertificateFile
-olcTLSCertificateFile: $STORAGE_ROOT/ssl/ssl_certificate.pem
--
 replace: olcTLSCertificateKeyFile
 olcTLSCertificateKeyFile: $STORAGE_ROOT/ssl/ssl_private_key.pem
 -
+replace: olcTLSCertificateFile
+olcTLSCertificateFile: $STORAGE_ROOT/ssl/ssl_certificate.pem
+-
+
 replace: olcTLSDHParamFile
 olcTLSDHParamFile: $STORAGE_ROOT/ssl/dh2048.pem
```

**Comment by hungrymonkey** [comment]
Nope. It happened with v62. It requires the domain to be unreachable to the instance. On the attempts I setup the dns, openssl works. On the other times, it fails.

**Comment by hungrymonkey** [comment]
```
]: Started Network Name Resolution.
]: Started Fail2Ban Service.
]: Stopping System Logging Service...
4873]: [origin software="rsyslogd" swVersion="8.2112.0" x-pid="4873" x-info="https://>
]: rsyslog.service: Deactivated successfully.
]: Stopped System Logging Service.
]: Starting System Logging Service...
]: Started System Logging Service.
5515]: imuxsock: Acquired UNIX socket '/run/systemd/journal/syslog' (fd 3) from syste>
5515]: rsyslogd's groupid changed to 111
5515]: rsyslogd's userid changed to 104
5515]: [origin software="rsyslogd" swVersion="8.2112.0" x-pid="5515" x-info="https://>
]: Reloading.
server[5507]: 2023-05-29 18:53:32,805 fail2ban                [5507]: ERROR   Failed >
server[5507]: 2023-05-29 18:53:32,883 fail2ban                [5507]: ERROR   Async c>
]: fail2ban.service: Main process exited, code=exited, status=255/EXCEPTION
]: fail2ban.service: Failed with result 'exit-code'.
]: fail2ban.service: Consumed 1.731s CPU time.
]: Reloading.
]: Started Monitor unattended upgrades and ensure ehdd services are started after upg>
]: Reloading.
]: Reloading.
]: Reloading.
5692]: group added to /etc/group: name=ssl-cert, GID=999
5692]: group added to /etc/gshadow: name=ssl-cert
5692]: new group: name=ssl-cert, GID=999
UFW BLOCK] IN=ens5 OUT= MAC=0a:5f:68:6b:f4:5f:0a:1c:ca:f9:e7:d2:08:00 SRC=192.241.238>
]: pam_unix(sudo:session): session closed for user root
4]:   validating domain.com/SOA: no valid signature found
4]: validating box.domain.com/A: no valid signature found
```

**Comment by downtownallday** [comment]
The tag/version issue described seems odd. I just did a clean
```
git clone https://github.com/downtownallday/mailinabox-ldap.git
cd mailinabox-ldap
git checkout v60
```
After that, `git describe` returns v60 and running setup in a fresh vagrant/jammy VM returns the same `Mail-in-a-Box Version:  v60`.

I'll see if I can test the DNS issue that you discovered `"It requires the domain to be unreachable to the instance"`. Does the existing DNS A or AAA record point to the miab-ldap instance? I guess it it didn't that would be strange, and I could see that might cause an issue.

**Comment by hungrymonkey** [comment]
@downtownallday . I might end up closing it as user error because the Openssl issue doesn't happen unless you become impatient and ctrl+C. It turns out after a few more minutes, it will give up and continue.

**Comment by downtownallday** [comment]
ok

**Comment by hungrymonkey** [comment]
Ahh, I learned a few behaviors such as the versioning is dependent by the tag.

I will try again. I will close this bug and figure out how to migrate from 57a -> 60.
