### ISSUE TITLE
Source of truth selector

### ISSUE THREAD

**Issue by writeDavid** [downtownallday/mailinabox-ldap#32]
This project looks amazing, thank you for all the hard work!

Are we able to have the LDAP database on its own Server? I currently have a LDAP Server, a NextCloud Server, and a MiaB Server. Looking to have the source of truth remain my LDAP Server, and just ldaps:// to it on both NextCloud and MiaB.

**Comment by downtownallday** [comment]
Thanks for stopping by. Any kind of enterprise feature like that would be too much work to maintain, and therefore I have no plans to do it.
