### ISSUE TITLE
Bug in nsd configuration on IPv6-enabled machines ("Public DNS (nsd4) is not running...")

### ISSUE THREAD

**Issue by dumblob** [downtownallday/mailinabox-ldap#4]
After successful fresh installation of MiaB-LDAP on a server with provably working dual-stack (IPv4 and IPv6) configuration, I noticed the following error in MiaB-LDAP web interface:

```
Public DNS (nsd4) is not running ([Errno 111] Connection refused; port 53)
```
I've looked in the log (`journalctl`) and found:
```
nsd[4973]: error: cannot parse address '2a02:25b0:abba:adda:278e:602b:1586:0': getaddrinfo: Address family for hostname not supported
```
(I've obfuscated the IP)

It turns out there is a bug in the script `setup/functions.sh`:
```
function kernel_ipv6_lo_disabled() {
        # Returns 0 if ipv6 is disabled on the loopback adapter
        local v="$(sysctl -n net.ipv6.conf.lo.disable_ipv6)"
        [ "$v" == "1" ] && return 0
        return 0
}
```
Which should actually read:
```
function kernel_ipv6_lo_disabled() {
        # Returns 0 if ipv6 is disabled on the loopback adapter
        local v="$(sysctl -n net.ipv6.conf.lo.disable_ipv6)"
        [ "$v" == "1" ] && return 0
        return 1
}
```
This is for Vargrant etc. deployment. It's used for `nsd` config file generation and generated wrong settings. I've changed nsd config manually until this gets fixed.

This was introduced about 3 months ago in https://github.com/downtownallday/mailinabox-ldap/commit/ae5fbffa408d503332d3c1bddcf97bf0fa28efe0#diff-f4c2e20a12be378580b63627b866502619cc2d2646557056260b6122617152e0 .

Would this be something to push to upstream MiaB?

@downtownallday could you fix it in this repo together with some next update? I don't think it's necessary to make a separate PR for this.

**Comment by downtownallday** [comment]
Good catch. I added this because of Travis CI, which disables IP6 in the kernel and nsd wouldn't start in that scenario. Upstream has no automated tests, so maybe this isn't of much use. I'll fix.
