### ISSUE TITLE
2FA from MiaB maybe incompatible with LDAP

### ISSUE THREAD

**Issue by dumblob** [downtownallday/mailinabox-ldap#6]
I just noticed TOTP 2-factor authentication got recently merged into MiaB. Skimming through the PR https://github.com/mail-in-a-box/mailinabox/pull/1814 I'm not sure LDAP backend will work on par with the DB backend.

E.g. the PR says:

>Handle attempts to enable/disable when credentials is present => handled by unique key constraint on db level

which might not work exactly the same with LDAP.

Maybe that's why you have the [tracking 2FA PR](https://github.com/downtownallday/mailinabox-ldap/pull/3 ) here?

**Comment by downtownallday** [comment]
I'm not exactly sure what that means. The "mfa" table doesn't even have a unique index on it. I believe it used to, so maybe the text didn't get updated.

**Comment by downtownallday** [comment]
TOTP 2FA was added, so am closing
