### ISSUE TITLE
I can see other contacts of ldap directory in roundcube

### ISSUE THREAD

**Issue by Ddataa** [downtownallday/mailinabox-ldap#7]
Hello,

Thanks a lot for your great work on this fork !!

I noticed that in roundcube every user can see each other adresses under contact / directory, is it normal ?
How can we prevent this to appear to keep only one Contact that would be the carddav backend ?

Thanks

**Comment by downtownallday** [comment]
Apologies for not replying sooner. I added this functionality because I wanted it for my own purposes. It's similar to what you'd see in G Suite.  To change it you'd have to fork and change setup/webmail.sh or change the Roundcube configuration every time setup runs.

**Comment by Ddataa** [comment]
ok thanks, I will have a look into it.

any hint on the part of the configuration I need to change to do so ?

**Comment by downtownallday** [comment]
you could remove the whole array "$config['ldap_public']['public']" in /usr/local/lib/roundcubemail/config/config.ini.php. You'd have to do that every time setup is run.

**Comment by Ddataa** [comment]
yes, perfect !

It could actually be helpful to keep it as well in different context.

Thanks a lot for your clear indications & help @downtownallday
