### ISSUE TITLE
install with Encryption-at-rest support

### ISSUE THREAD

**Issue by Ddataa** [downtownallday/mailinabox-ldap#9]
Regarding the install with encryption at rest documentation here https://github.com/downtownallday/mailinabox-ldap/tree/master/ehdd

There is no script `ehdd/setup-encrypted.sh` but instead `ehdd/start-encrypted.sh` is available, can you confirm it is the right script to start install ?

Thanks a lot !

**Comment by downtownallday** [comment]
You are correct

**Comment by Ddataa** [comment]
Thanks for your answer and confirmation @downtownallday ;)
